sudo: false

language: node_js

node_js: "0.12"

install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g coveralls
  - npm install -g mocha-lcov-reporter
  - npm install
services:
  - redis-server
  - mongodb
before_install:  
  - sleep 5
script:
  - istanbul cover _mocha --report lcovonly
after_script:
  - cat ./coverage/lcov.info | coveralls
