language: node_js

node_js: "0.10"

install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g coveralls
  - npm install -g mocha-lcov-reporter
  - npm install
services:
  - redis-server
before_install:  
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org mongodb-org-server mongodb-org-shell mongodb-org-mongos mongodb-org-tools"
  - sleep 15
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
script:
  - istanbul cover _mocha --report lcovonly
after_script:
  - cat ./coverage/lcov.info | coveralls
